Renamed accounts to envs

diff --git a/.github/workflows/build-push.yml b/.github/workflows/build-push.yml
--- a/.github/workflows/build-push.yml
+++ b/.github/workflows/build-push.yml
@@ -4,8 +4,11 @@ on:
   push:
     branches: [ main ]
 
+env:
+  TF_VERSION: 1.3.7
+
 jobs:
-  build-and-push:
+  build-and-push-dev:
     name: Build and Push Image - Dev
     runs-on: ubuntu-latest
     steps:
@@ -60,3 +63,40 @@ jobs:
       run: |
         docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
         docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
+
+  deploy-dev:
+    name: Deploy Dev Environment
+    needs: build-and-push-dev
+    environment:
+      name: dev
+      url: "http://platform-lb-dev-205457050.eu-west-2.elb.amazonaws.com"
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+        id: checkout
+        name: Checkout source code
+
+      - name: Setup AWS credentials
+        run: |
+          mkdir ~/.aws
+          echo -e "[default]\naws_access_key_id=${{ secrets.TF_USER_AWS_KEY }}\naws_secret_access_key=${{ secrets.TF_USER_AWS_SECRET }}\n" >> ~/.aws/credentials
+
+      - uses: hashicorp/setup-terraform@v2
+        with:
+          terraform_version: ${{ env.TF_VERSION }}
+
+      - name: Terraform Format
+        id: fmt
+        working-directory: "envs/dev/ecs"
+        run: |
+          terraform fmt -check -diff -recursive && echo -e "\e[32mterraform fmt succeeded!\e[0m" || (echo -e "\e[31mterraform fmt failed! Install the precommit hooks!\e[0m" && exit 1)
+
+      - name: Terraform Init
+        working-directory: "envs/dev/ecs"
+        run: terraform init
+
+      - name: Terraform Apply
+        working-directory: "envs/dev/ecs"
+        env:
+          TF_IN_AUTOMATION: 1
+        run: terraform apply -auto-approve -input=false -compact-warnings
